# TCL File Generated by Component Editor 10.1sp1
# Fri Jun 24 16:37:52 CST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SOPC_PNLPort "Panel Port Controller" v1.0
# | shyul 2011.06.24.16:37:52
# | 
# | 
# | D:/Project/_BuildBlock/Hardware/EXB-100/Testbench/EXB-100-U1-C8051F/sopc_root/SOPC_PNLPort.v
# | 
# |    ./SOPC_PNLPort.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module SOPC_PNLPort
# | 
set_module_property NAME SOPC_PNLPort
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "EXB-100-C8051/User Interface"
set_module_property AUTHOR shyul
set_module_property DISPLAY_NAME "Panel Port Controller"
set_module_property TOP_LEVEL_HDL_FILE SOPC_PNLPort.v
set_module_property TOP_LEVEL_HDL_MODULE PNLPort
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SOPC_PNLPort.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0

set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point addr
# | 
add_interface addr avalon end
set_interface_property addr addressAlignment DYNAMIC
set_interface_property addr addressUnits WORDS
set_interface_property addr associatedClock clockreset
set_interface_property addr burstOnBurstBoundariesOnly false
set_interface_property addr explicitAddressSpan 0
set_interface_property addr holdTime 0
set_interface_property addr isMemoryDevice false
set_interface_property addr isNonVolatileStorage false
set_interface_property addr linewrapBursts false
set_interface_property addr maximumPendingReadTransactions 0
set_interface_property addr printableDevice false
set_interface_property addr readLatency 0
set_interface_property addr readWaitTime 1
set_interface_property addr setupTime 0
set_interface_property addr timingUnits Cycles
set_interface_property addr writeWaitTime 0

set_interface_property addr ENABLED true

add_interface_port addr avs_addr_readdata readdata Output 8
add_interface_port addr avs_addr_writedata writedata Input 8
add_interface_port addr avs_addr_write_n write_n Input 1
add_interface_port addr avs_addr_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point key0
# | 
add_interface key0 avalon end
set_interface_property key0 addressAlignment DYNAMIC
set_interface_property key0 addressUnits WORDS
set_interface_property key0 associatedClock clockreset
set_interface_property key0 burstOnBurstBoundariesOnly false
set_interface_property key0 explicitAddressSpan 0
set_interface_property key0 holdTime 0
set_interface_property key0 isMemoryDevice false
set_interface_property key0 isNonVolatileStorage false
set_interface_property key0 linewrapBursts false
set_interface_property key0 maximumPendingReadTransactions 0
set_interface_property key0 printableDevice false
set_interface_property key0 readLatency 0
set_interface_property key0 readWaitTime 1
set_interface_property key0 setupTime 0
set_interface_property key0 timingUnits Cycles
set_interface_property key0 writeWaitTime 0

set_interface_property key0 ENABLED true

add_interface_port key0 avs_key0_readdata readdata Output 8
add_interface_port key0 avs_key0_writedata writedata Input 8
add_interface_port key0 avs_key0_write_n write_n Input 1
add_interface_port key0 avs_key0_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point key1
# | 
add_interface key1 avalon end
set_interface_property key1 addressAlignment DYNAMIC
set_interface_property key1 addressUnits WORDS
set_interface_property key1 associatedClock clockreset
set_interface_property key1 burstOnBurstBoundariesOnly false
set_interface_property key1 explicitAddressSpan 0
set_interface_property key1 holdTime 0
set_interface_property key1 isMemoryDevice false
set_interface_property key1 isNonVolatileStorage false
set_interface_property key1 linewrapBursts false
set_interface_property key1 maximumPendingReadTransactions 0
set_interface_property key1 printableDevice false
set_interface_property key1 readLatency 0
set_interface_property key1 readWaitTime 1
set_interface_property key1 setupTime 0
set_interface_property key1 timingUnits Cycles
set_interface_property key1 writeWaitTime 0

set_interface_property key1 ENABLED true

add_interface_port key1 avs_key1_readdata readdata Output 8
add_interface_port key1 avs_key1_writedata writedata Input 8
add_interface_port key1 avs_key1_write_n write_n Input 1
add_interface_port key1 avs_key1_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point key2
# | 
add_interface key2 avalon end
set_interface_property key2 addressAlignment DYNAMIC
set_interface_property key2 addressUnits WORDS
set_interface_property key2 associatedClock clockreset
set_interface_property key2 burstOnBurstBoundariesOnly false
set_interface_property key2 explicitAddressSpan 0
set_interface_property key2 holdTime 0
set_interface_property key2 isMemoryDevice false
set_interface_property key2 isNonVolatileStorage false
set_interface_property key2 linewrapBursts false
set_interface_property key2 maximumPendingReadTransactions 0
set_interface_property key2 printableDevice false
set_interface_property key2 readLatency 0
set_interface_property key2 readWaitTime 1
set_interface_property key2 setupTime 0
set_interface_property key2 timingUnits Cycles
set_interface_property key2 writeWaitTime 0

set_interface_property key2 ENABLED true

add_interface_port key2 avs_key2_readdata readdata Output 8
add_interface_port key2 avs_key2_writedata writedata Input 8
add_interface_port key2 avs_key2_write_n write_n Input 1
add_interface_port key2 avs_key2_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point key3
# | 
add_interface key3 avalon end
set_interface_property key3 addressAlignment DYNAMIC
set_interface_property key3 addressUnits WORDS
set_interface_property key3 associatedClock clockreset
set_interface_property key3 burstOnBurstBoundariesOnly false
set_interface_property key3 explicitAddressSpan 0
set_interface_property key3 holdTime 0
set_interface_property key3 isMemoryDevice false
set_interface_property key3 isNonVolatileStorage false
set_interface_property key3 linewrapBursts false
set_interface_property key3 maximumPendingReadTransactions 0
set_interface_property key3 printableDevice false
set_interface_property key3 readLatency 0
set_interface_property key3 readWaitTime 1
set_interface_property key3 setupTime 0
set_interface_property key3 timingUnits Cycles
set_interface_property key3 writeWaitTime 0

set_interface_property key3 ENABLED true

add_interface_port key3 avs_key3_readdata readdata Output 8
add_interface_port key3 avs_key3_writedata writedata Input 8
add_interface_port key3 avs_key3_write_n write_n Input 1
add_interface_port key3 avs_key3_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ctrl
# | 
add_interface ctrl avalon end
set_interface_property ctrl addressAlignment DYNAMIC
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clockreset
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl isMemoryDevice false
set_interface_property ctrl isNonVolatileStorage false
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl printableDevice false
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0

set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_readdata readdata Output 8
add_interface_port ctrl avs_ctrl_writedata writedata Input 8
add_interface_port ctrl avs_ctrl_write_n write_n Input 1
add_interface_port ctrl avs_ctrl_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point event
# | 
add_interface event interrupt end
set_interface_property event associatedAddressablePoint addr
set_interface_property event associatedClock clockreset

set_interface_property event ENABLED true

add_interface_port event ins_event_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT PNL_DO export Output 1
add_interface_port EXPORT PNL_DI export Input 1
add_interface_port EXPORT PNL_CLK export Input 1
add_interface_port EXPORT PNL_LE export Input 1
add_interface_port EXPORT PNL_STA export Input 1
# | 
# +-----------------------------------
