# TCL File Generated by Component Editor 10.0sp1
# Wed Jun 15 17:29:47 CST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SOPC_IntKey "Intrq Key Interface 8-bit" v1.0
# | Jeff K. 2011.06.15.17:29:47
# | 
# | 
# | D:/Project/_BuildBlock/Hardware/EXB-100/Testbench/EXB-100-U1-C8051F/sopc_root/SOPC_IntKey.v
# | 
# |    ./SOPC_IntKey.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module SOPC_IntKey
# | 
set_module_property NAME SOPC_IntKey
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP EXB-100-C8051/Basic
set_module_property AUTHOR "Jeff K."
set_module_property DISPLAY_NAME "Intrq Key Interface 8-bit"
set_module_property TOP_LEVEL_HDL_FILE SOPC_IntKey.v
set_module_property TOP_LEVEL_HDL_MODULE SOPC_IntKey
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SOPC_IntKey.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end

set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point intkey
# | 
add_interface intkey avalon end
set_interface_property intkey addressAlignment DYNAMIC
set_interface_property intkey associatedClock clockreset
set_interface_property intkey burstOnBurstBoundariesOnly false
set_interface_property intkey explicitAddressSpan 0
set_interface_property intkey holdTime 0
set_interface_property intkey isMemoryDevice false
set_interface_property intkey isNonVolatileStorage false
set_interface_property intkey linewrapBursts false
set_interface_property intkey maximumPendingReadTransactions 0
set_interface_property intkey printableDevice false
set_interface_property intkey readLatency 0
set_interface_property intkey readWaitTime 1
set_interface_property intkey setupTime 0
set_interface_property intkey timingUnits Cycles
set_interface_property intkey writeWaitTime 0

set_interface_property intkey ASSOCIATED_CLOCK clockreset
set_interface_property intkey ENABLED true

add_interface_port intkey avs_intkey_readdata readdata Output 8
add_interface_port intkey avs_intkey_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point intrq
# | 
add_interface intrq interrupt end
set_interface_property intrq associatedAddressablePoint intkey
set_interface_property intrq associatedClock clockreset

set_interface_property intrq ASSOCIATED_CLOCK clockreset
set_interface_property intrq ENABLED true

add_interface_port intrq ins_intrq_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT INT_KEY beginbursttransfer_n Input 1
# | 
# +-----------------------------------
