# TCL File Generated by Component Editor 10.0sp1
# Wed Jun 15 17:26:18 CST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SOPC_ChipID "Chip ID 8-bit" v1.0
# | Jeff K. 2011.06.15.17:26:18
# | 
# | 
# | D:/Project/_BuildBlock/Hardware/EXB-100/Testbench/EXB-100-U1-C8051F/sopc_root/SOPC_ChipID.v
# | 
# |    ./SOPC_ChipID.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module SOPC_ChipID
# | 
set_module_property NAME SOPC_ChipID
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP EXB-100-C8051/Basic
set_module_property AUTHOR "Jeff K."
set_module_property DISPLAY_NAME "Chip ID 8-bit"
set_module_property TOP_LEVEL_HDL_FILE SOPC_ChipID.v
set_module_property TOP_LEVEL_HDL_MODULE ChipID
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SOPC_ChipID.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end

set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point idout
# | 
add_interface idout avalon end
set_interface_property idout addressAlignment DYNAMIC
set_interface_property idout associatedClock clockreset
set_interface_property idout burstOnBurstBoundariesOnly false
set_interface_property idout explicitAddressSpan 0
set_interface_property idout holdTime 0
set_interface_property idout isMemoryDevice false
set_interface_property idout isNonVolatileStorage false
set_interface_property idout linewrapBursts false
set_interface_property idout maximumPendingReadTransactions 0
set_interface_property idout printableDevice false
set_interface_property idout readLatency 0
set_interface_property idout readWaitTime 1
set_interface_property idout setupTime 0
set_interface_property idout timingUnits Cycles
set_interface_property idout writeWaitTime 0

set_interface_property idout ASSOCIATED_CLOCK clockreset
set_interface_property idout ENABLED true

add_interface_port idout avs_idout_readdata readdata Output 8
add_interface_port idout avs_idout_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------
