# TCL File Generated by Component Editor 10.0sp1
# Wed Jun 15 17:28:39 CST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SOPC_OptionKey "Option Key Interface 8-bit" v1.0
# | Jeff K. 2011.06.15.17:28:39
# | 
# | 
# | D:/Project/_BuildBlock/Hardware/EXB-100/Testbench/EXB-100-U1-C8051F/sopc_root/SOPC_OptionKey.v
# | 
# |    ./SOPC_OptionKey.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module SOPC_OptionKey
# | 
set_module_property NAME SOPC_OptionKey
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP EXB-100-C8051/Basic
set_module_property AUTHOR "Jeff K."
set_module_property DISPLAY_NAME "Option Key Interface 8-bit"
set_module_property TOP_LEVEL_HDL_FILE SOPC_OptionKey.v
set_module_property TOP_LEVEL_HDL_MODULE SOPC_OptionKey
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SOPC_OptionKey.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end

set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point optkey
# | 
add_interface optkey avalon end
set_interface_property optkey addressAlignment DYNAMIC
set_interface_property optkey associatedClock clockreset
set_interface_property optkey burstOnBurstBoundariesOnly false
set_interface_property optkey explicitAddressSpan 0
set_interface_property optkey holdTime 0
set_interface_property optkey isMemoryDevice false
set_interface_property optkey isNonVolatileStorage false
set_interface_property optkey linewrapBursts false
set_interface_property optkey maximumPendingReadTransactions 0
set_interface_property optkey printableDevice false
set_interface_property optkey readLatency 0
set_interface_property optkey readWaitTime 1
set_interface_property optkey setupTime 0
set_interface_property optkey timingUnits Cycles
set_interface_property optkey writeWaitTime 0

set_interface_property optkey ASSOCIATED_CLOCK clockreset
set_interface_property optkey ENABLED true

add_interface_port optkey avs_optkey_readdata readdata Output 8
add_interface_port optkey avs_optkey_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT OPT_IN writebyteenable_n Input 4
# | 
# +-----------------------------------
