# TCL File Generated by Component Editor 10.0sp1
# Wed Jun 15 17:32:10 CST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SOPC_MemLCD "LCD Interface for T6963C" v1.0
# | Jeff K. / Shyu L. 2011.06.15.17:32:10
# | 
# | 
# | D:/Project/_BuildBlock/Hardware/EXB-100/Testbench/EXB-100-U1-C8051F/sopc_root/SOPC_MemLCD.v
# | 
# |    ./SOPC_MemLCD.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module SOPC_MemLCD
# | 
set_module_property NAME SOPC_MemLCD
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "EXB-100-C8051/User Interface"
set_module_property AUTHOR "Jeff K. / Shyu L."
set_module_property DISPLAY_NAME "LCD Interface for T6963C"
set_module_property TOP_LEVEL_HDL_FILE SOPC_MemLCD.v
set_module_property TOP_LEVEL_HDL_MODULE MemLCD
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SOPC_MemLCD.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end

set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point lcd
# | 
add_interface lcd avalon end
set_interface_property lcd addressAlignment DYNAMIC
set_interface_property lcd associatedClock clockreset
set_interface_property lcd burstOnBurstBoundariesOnly false
set_interface_property lcd explicitAddressSpan 0
set_interface_property lcd holdTime 0
set_interface_property lcd isMemoryDevice false
set_interface_property lcd isNonVolatileStorage false
set_interface_property lcd linewrapBursts false
set_interface_property lcd maximumPendingReadTransactions 0
set_interface_property lcd printableDevice false
set_interface_property lcd readLatency 0
set_interface_property lcd readWaitTime 1
set_interface_property lcd setupTime 0
set_interface_property lcd timingUnits Cycles
set_interface_property lcd writeWaitTime 0

set_interface_property lcd ASSOCIATED_CLOCK clockreset
set_interface_property lcd ENABLED true

add_interface_port lcd avs_lcd_readdata readdata Output 8
add_interface_port lcd avs_lcd_writedata writedata Input 8
add_interface_port lcd avs_lcd_address address Input 1
add_interface_port lcd avs_lcd_chipselect_n chipselect_n Input 1
add_interface_port lcd avs_lcd_write_n write_n Input 1
add_interface_port lcd avs_lcd_read_n read_n Input 1
add_interface_port lcd avs_lcd_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT LCD_DATA export Bidir 16
add_interface_port EXPORT LCD_CTRL export Output 4
add_interface_port EXPORT LCD_BUF_DIR export Output 1
# | 
# +-----------------------------------
