# TCL File Generated by Component Editor 10.0sp1
# Wed Jun 15 17:35:33 CST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SOPC_ATAPort "8-bit Parallel I/O for C8051F" v1.0
# | Jeff K. / Shyu L. 2011.06.15.17:35:33
# | 
# | 
# | D:/Project/_BuildBlock/Hardware/EXB-100/Testbench/EXB-100-U1-C8051F/sopc_root/SOPC_ATAPort.v
# | 
# |    ./SOPC_ATAPort.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module SOPC_ATAPort
# | 
set_module_property NAME SOPC_ATAPort
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP EXB-100-C8051/Expansion
set_module_property AUTHOR "Jeff K. / Shyu L."
set_module_property DISPLAY_NAME "8-bit Parallel I/O for C8051F"
set_module_property TOP_LEVEL_HDL_FILE SOPC_ATAPort.v
set_module_property TOP_LEVEL_HDL_MODULE ATAPort
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SOPC_ATAPort.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end

set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ata
# | 
add_interface ata avalon end
set_interface_property ata addressAlignment DYNAMIC
set_interface_property ata associatedClock clockreset
set_interface_property ata burstOnBurstBoundariesOnly false
set_interface_property ata explicitAddressSpan 0
set_interface_property ata holdTime 0
set_interface_property ata isMemoryDevice false
set_interface_property ata isNonVolatileStorage false
set_interface_property ata linewrapBursts false
set_interface_property ata maximumPendingReadTransactions 0
set_interface_property ata printableDevice false
set_interface_property ata readLatency 0
set_interface_property ata readWaitTime 1
set_interface_property ata setupTime 0
set_interface_property ata timingUnits Cycles
set_interface_property ata writeWaitTime 0

set_interface_property ata ASSOCIATED_CLOCK clockreset
set_interface_property ata ENABLED true

add_interface_port ata avs_ata_readdata readdata Output 8
add_interface_port ata avs_ata_writedata writedata Input 8
add_interface_port ata avs_ata_address address Input 5
add_interface_port ata avs_ata_chipselect_n chipselect_n Input 1
add_interface_port ata avs_ata_write_n write_n Input 1
add_interface_port ata avs_ata_read_n read_n Input 1
add_interface_port ata avs_ata_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point intrq
# | 
add_interface intrq interrupt end
set_interface_property intrq associatedAddressablePoint ata
set_interface_property intrq associatedClock clockreset

set_interface_property intrq ASSOCIATED_CLOCK clockreset
set_interface_property intrq ENABLED true

add_interface_port intrq ins_intrq_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT ATA_DATA export Bidir 16
add_interface_port EXPORT ATA_ADDR export Output 5
add_interface_port EXPORT ATA_OEN export Output 1
add_interface_port EXPORT ATA_WEN export Output 1
add_interface_port EXPORT ATA_WAITN export Input 1
add_interface_port EXPORT ATA_INTRQ export Input 1
add_interface_port EXPORT ATA_DATA_DIR export Output 1
# | 
# +-----------------------------------
